language: cpp

compiler:
  - gcc
  - clang

cache: apt

addons:
  apt:
    packages:
    - g++-4.9
    
install:
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

script: make -j

notifications:
  email: false

matrix:
  fast_finish: true
