language: cpp

compiler:
  - gcc
  - clang

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    
install:
  export CC=gcc-4.9
  export CXX=g++-4.9

script: make -j

notifications:
  email: false

matrix:
  fast_finish: true
